version: '3.8'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: db_postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: jean
    volumes:
      - ./scripts/postgres:/data/postgres
    ports:
      - '5432'
    restart: always

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./scripts/pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:jean:123' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

networks:
  default:
    name: local-network
    external: true